#title in header
title: ngtrio.me

#main info
#owner
owner: Welcome and have fun :D
email: ngtercet@protonmail.com
info: 
#description
desc: 

#menu
menu:
  Archive: /archives
  Tags: /tags
  About: /about

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/ngtrio
# linkedin:
# twitter:
# instagram:
stackoverflow: https://stackoverflow.com/users/11571735/ngtercet
zhihu: https://www.zhihu.com/people/innun

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io


cc: /images/by-nc-sa.svg