name: auto deploy

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-latest

    steps:

      - name: Checkout to main
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
          
      - name: Setup Git
        env:
          DEPLOY_SECRET: ${{ secrets.DEPLOY_SECRET }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_SECRET" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "ngtercet@protonmail.com"
          git config --global user.name "Jaron"
          
      - name: Setup Hexo
        run: |
          npm install hexo-cli -g
          npm install
        
      - name: Deploy
        run: |
          hexo clean
          hexo deploy
